--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NopeNotDark/CrypticOpFactions
build-by-default: true
branches:
- master
projects:
  CrypticOpFactions:
    path: ""
    lint:
        phpstan: false
libs:
      - src: muqsit/invmenu/InvMenu
      version: ^3.2.0
...
